services:
  accounts:
    image: amrbadawy1/accounts:latest
    container_name: accounts
    ports:
      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
#      - postgres
#      - rabbitmq
  cards:
    image: amrbadawy1/cards:latest
    container_name: cards
    ports:
      - "8081:8081"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
#      - postgres
#      - rabbitmq
  loans:
    image: amrbadawy1/loans:latest
    container_name: loans
    ports:
      - "8082:8082"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
#      - postgres
#      - rabbitmq
networks:
  spring:
    driver: bridge
